name: "Continuous Build (.NET)"

on:
  push:
    paths:
      - '*'
    branches:
      - main
  pull_request:
    paths:
      - 'dotnet/**'
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        if: ${{ matrix.language == 'dotnet' }}
        with:
          dotnet-version: '6.0.x'
      - name: Build .NET layer for arm64
        run: GOARCH="arm64" ./build.sh
        working-directory: "dotnet/sample-apps/aws-sdk/wrapper/SampleApps"
      - name: Build .NET layer for amd64
        run: GOARCH="amd64" ./build.sh
        working-directory: "dotnet/sample-apps/aws-sdk/wrapper/SampleApps"
